version: 2

models:
  - name: agg_web_lessons__completed
    description: "Calculates all aggregated lesson completed data on web."
    config:
      labels:
        project: "oppia-web-analytics"
        owner: "analytics-team"
    columns:
      - name: user_id
        description: "The unique identifier for the user."
        tests:
          - not_null
      - name: lesson_id
        description: "The unique identifier for the lesson."
        tests:
          - not_null
      - name: updated_date
        description: "The UTC date when the lesson progress was recorded. Used as the table partition key."
        tests:
          - not_null
